### ISSUE TITLE
separate files

### ISSUE THREAD

**Issue by ghost** [steffenwt/nodejs-pub-sub-chat-demo#1]
I'm having problems when pulling anything out and putting it in a separate file. 

The error is: Uncaught SyntaxError: Unexpected token < 
Always on the first line.

Can't seem to work around it. Perhaps an error in the JS somewhere?  I don't see where.
Are you able to put the JS from this in a separate file?

**Comment by steffenwt** [comment]
Should be solved with latest merge.
