### ISSUE TITLE
Outdated Code

### ISSUE THREAD

**Issue by dlbrown06** [steffenwt/nodejs-pub-sub-chat-demo#3]
In your readme you specify to `npm install redis socket.io`. Doing this will install the latest versions without a `package.json` specifying the versions that are required. Current code base doesn't work with recent versions of socket.io

**Comment by D-side** [comment]
You could pick a version that was actual at that time using **[`socket.io` releases page](https://github.com/Automattic/socket.io/releases)**. It has a nice table with all the releases, each one with a date. **`0.9.0`** should be close enough, judging by the date of last commit here. Can't test that out myself, sorry, but if you still need that, it's the best chance you have.

*Project's own `package.json` could be of use, that's for sure.*
